@url = http://localhost:8080/api/relationship
@auth = "3glSSBIifYFmaVeY5sXphXnaepNG2gvBcp3j2zbeYq0="

###
# delete happy path
DELETE {{url}}/1
Authorization: {{auth}}
Content-Type: application/json

{
    "email": "a@a.com",
    "id": 1
}
